version: '3.8'

services:
  postgres_test:
    image: postgres
    container_name: postgres_db_test
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgresql-data:/var/lib/postgresql_test/data
